<?php

namespace Container4s9141F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R6YxH7SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r6YxH7S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r6YxH7S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.r6YxH7S.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.r6YxH7S": it references class "App\\Entity\\Course" but no such service exists.'],
        ], [
            'course' => 'App\\Entity\\Course',
        ]);
    }
}
