<?php

namespace Container4s9141F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Kdg6TWc.App\Entity\Video' shared service.
     *
     * @return \App\Entity\Video
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Kdg6TWc": it references class "App\\Entity\\Video" but no such service exists.');
    }
}
