<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlaItKN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlaItKN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGlaItKN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGlaItKN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGlaItKN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GlaItKN',
    'container.build_id' => '7d3426cb',
    'container.build_time' => 1640271958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlaItKN');
